### ISSUE TITLE
Cannot Download Windows Version

### ISSUE THREAD

**Issue by muhginanjar** [sfx101/docker-stacks#125]
Hello,

I cannot download deck for windows, i try to access to https://get-deck.com/download-windows/ but it always return to error.
would you help me?

**Comment by nabad600** [comment]
Hi @muhginanjar, 
Thanks for choosing  DECK. This is a Github issue,
please find the attachment.
![image](https://user-images.githubusercontent.com/67466982/216955221-559c3845-3ac5-48e9-a863-9c148dd0c820.png)

**Comment by muhginanjar** [comment]
I see "no current problems"

**Comment by nabad600** [comment]
Hi, @muhginanjar,

Can you check now.

**Comment by muhginanjar** [comment]
Thanks alot, now i can download it. 
Thank you so much.

**Comment by nabad600** [comment]
Thank
