### ISSUE TITLE
Install will fail if deck previously installed

### ISSUE THREAD

**Issue by sjregan** [sfx101/docker-stacks#135]
After deleting all Deck related files and re-installing MacOS 4.2.0, Deck will try and setup multipass and fail:

```
echo -e '\x1bc' && sh /Applications/DECK.app/Contents/Resources/scripts/installe
❯ echo -e '' && sh /Applications/DECK.app/Contents/Resources/scripts/installer.sh /Applications/DECK.app/Contents/Resources/multipass/multipass.pkg ; exit

Skipping download, Multipass is already installed
ca7747dfcae5ee948ffee4c81099b1a4
Creating a lightweight Ubuntu VM, this will take a few mins ...
launch failed: instance "deck-app" already exists                               


30cc5285d6bc297b9ca633042957def0                                                
exec failed: instance "deck-app" is not running
```

**Comment by nabad600** [comment]
Hi @sjregan, Thank you for your feedback,
Your MacOS version is 4.2.0. Can you please upgrade to the MacOS version to at least 10.15.7, and try once to check if the issue persists or not? 
We'd be happy to help.

**Comment by sjregan** [comment]
@nabad600 My MacOS version is 12.6. I am referring to Deck version 4.2.0 for MacOS.

**Comment by nabad600** [comment]
Hi @sjregan, Could you please do the following?
1. Open the deck app and go to setting, click on Docker engine & uncheck Remote engine

![image](https://user-images.githubusercontent.com/67466982/223976228-1380b7b3-91df-453f-abd2-38a50da06b78.png)

2. Open terminal and Uninstall multipass using `sudo sh "/Library/Application Support/com.canonical.multipass/uninstall.sh"`
3. Restart the deck app

The above should reinstall correctly,

**Comment by sjregan** [comment]
@nabad600 Thanks, I was able to previously install the app by uninstalling multipass. It would be nice if there was a clean upgrade path built into the app rather than requiring running terminal commands.

**Comment by nabad600** [comment]
HI, @sjregan, Thank you so much for sharing your feedback,
sure, we'll look into this in our future releases. currently, we are closing this ticket.
