### ISSUE TITLE
php 7.1 and 7.2 

### ISSUE THREAD

**Issue by baaslaawe** [sfx101/docker-stacks#137]
there's no php 7.1 i want ....

**Comment by nabad600** [comment]
Hi @baaslaawe, We'll shortly be integrating the marketplace into versions 7.1 and 7.2. I'll update you on my progress. Ty

**Comment by baaslaawe** [comment]
we use codeigniter 3 still how long

**Comment by nabad600** [comment]
Hi @baaslaawe, PHP 7.2 & 7.1 is released, Let us know of any issues, we'd be happy to help.

**Comment by nabad600** [comment]
Hi @baaslaawe,
We may need to close this ticket in the next 24 hours. So, I request you to inform us about the status of your query.
Let us know of any issues, we'd be happy to help.
