### ISSUE TITLE
Not able to install Laravel on Windows

### ISSUE THREAD

**Issue by sanjayojha** [sfx101/docker-stacks#138]
I have used deck in past and then uninstalled it. I had to delete some files manually at that time. Today, I am trying to install it again. But I am getting following error when installing Laravel.

![13 04 2023_16 26 48_REC](https://user-images.githubusercontent.com/3258151/231738596-87c14bfd-d681-47af-bc5f-cca6c8df7cdb.png)

I am using Windows 11.

**Comment by nabad600** [comment]
Hi @sanjayojha, 
Thank you for using DECK, I think you have selected PHP v8.x and getting the issue. We are working on it. 
Meanwhile, if you are choosing PHP v8.x, don't select "PHP extensions". Next release the issue will be resolved.


reference:- https://github.com/deck-app/laravel/issues/9
![image](https://user-images.githubusercontent.com/67466982/231770853-7e7a0752-75b9-4d8a-8bcc-5a71d15ab383.png)

**Comment by sanjayojha** [comment]
@nabad600 , thank you.
Yes it worked for remote engine. But if I select Docker desktop, it still doesn't work.

**Comment by nabad600** [comment]
Hi @sanjayojha,
Thank you for your reply, when selecting Docker desktop then uncheck the "remote engine" option, for reference 
![image](https://user-images.githubusercontent.com/67466982/231946271-7ed72787-bc5a-4924-9d4c-a6d6d80abef1.png)

**Comment by sanjayojha** [comment]
@nabad600 
Ya, I did exactly that. But it doesn't work. So I checked it, restarted and it worked.

**Comment by nabad600** [comment]
Hi @sanjayojha 
We've fixed the issue. We'd be happy to help.

> I have used deck in past and then uninstalled it. I had to delete some files manually at that time. Today, I am trying to install it again. But I am getting following error when installing Laravel.
> 
> ![13 04 2023_16 26 48_REC](https://user-images.githubusercontent.com/3258151/231738596-87c14bfd-d681-47af-bc5f-cca6c8df7cdb.png)
> 
> I am using Windows 11.
