### ISSUE TITLE
No README found / Invalid github link.

### ISSUE THREAD

**Issue by fadymondy** [sfx101/docker-stacks#144]
when try to install any stack I get a message 

No README found

when I click install

Invalid GitHub link.

I try to restart it many times

OS: MacOS 14

**Comment by sfx101** [comment]
Hi @3x1io, the app fetches the readme from GitHub. Most likely, there was a temporary ban on your IP by them. If you retry later, the issue should be fixed by itself. Thank you for trying out DECK!
