### ISSUE TITLE
Laravel 11 and PHP 8.3 Not Yet Available

### ISSUE THREAD

**Issue by luchtech** [sfx101/docker-stacks#156]
Hi, guys! Just tried your app earlier. It's really cool so far! This is a better alternative for Laravel Herd tbh.

I just noticed that it does not have Laravel 11 option as well as option for PHP 8.3.

Also, is it possible for you guys to have a Laravel stack that uses Spin Docker images by ServerSideUp? They seem to have something for development and one for production use.

Kudos!

**Comment by sfx101** [comment]
@luchtech closing this as you've already created a PR for it, thanks!
