### ISSUE TITLE
Discord Group anyone? This could be the Laravel Herd Killer.

### ISSUE THREAD

**Issue by luchtech** [sfx101/docker-stacks#158]
Hi!

I've already touched on this app long before but I did not see it's potential yet. I was a fool!

When Laravel Herd was dropped, I really think yours is better as it works very well with Docker already. And if a newbie did not have Docker, there's Multipass! You've thought it very well!

I think it would be better if there's a Discord group where Laravel devs, old and new, can contribute and have a discussion.

I hope you will be motivated as Laravel Herd is something you can beat.

Good job and good luck!

**Comment by sfx101** [comment]
Hi @luchtech , thank you for your comment; that means a lot! Unfortunately, our team is quite busy w/ daily work so we aren't able to work on this project. When we started DECK we knew it's something different and people like you would love it but you know things don't always go the right way and we have to focus on other things on the plate :)

**Comment by luchtech** [comment]
I see. It's so sad to let this app go. :( Can you open-source it so interested people can continue it? 😅 I feel like Laravel Herd is pushing people to get the Pro License just to have a basic MySQL server. Or a Redis server or a Mail Server. Your work seems to be the best contender atm. The UI is really cool!

I hope you'll reconsider abandoning it. 🥲

**Comment by sfx101** [comment]
@luchtech the full source code is already in the master branch of this repo. The tech stack is Electron js, Svelte

**Comment by luchtech** [comment]
Will the Discord Group be a good idea?

**Comment by sfx101** [comment]
@luchtech let's stick to Github issues for the moment until we have more users requesting, Appreciate your efforts, tysm!
