### ISSUE TITLE
Custom Stack from Github URL?

### ISSUE THREAD

**Issue by luchtech** [sfx101/docker-stacks#161]
Hi! I've been trying this cool feature you have called Custom Stack. I am currently building one. I think it is ready but I don't know how to share it with my friends.

Is there another way aside from LocalPath?

<img width="2032" alt="image" src="https://github.com/sfx101/deck/assets/26067874/e4bf992d-10e7-47eb-9bd9-45bbff6ce82a">

**Comment by SUPERNOVI** [comment]
Hey, completely untested but I think it might be:

`"@Github": "deck-app/apache-stack"`

I found this in the stacks.json.

Don't expect a response from the owners or developers. It kind of feels like this project is abandoned.

**Comment by sfx101** [comment]
> Hey, completely untested but I think it might be:
> 
> `"@Github": "deck-app/apache-stack"`
> 
> I found this in the stacks.json.
> 
> Don't expect a response from the owners or developers. It kind of feels like this project is abandoned.

Yes, that is the way to do it, should be a public repo of course.
