### ISSUE TITLE
HTTPS is not working suddenly

### ISSUE THREAD

**Issue by luchtech** [sfx101/docker-stacks#163]
All of a sudden, I am seeing an error with the HTTPS url. Any ideas?

<img width="333" alt="image" src="https://github.com/sfx101/deck/assets/26067874/6e5ea250-6207-43b6-8879-ff5ab20396a4">

<img width="765" alt="image" src="https://github.com/sfx101/deck/assets/26067874/74fa33cc-0cb4-4973-a51d-c4a7c1802224">

**Comment by sfx101** [comment]
@nabad600, can you please check this as a priority? The cert has expired.

**Comment by SUPERNOVI** [comment]
Yes same problem here.

This is a really serious problem!

**Comment by sfx101** [comment]
Please restart the app, the issue should be fixed now.
