### ISSUE TITLE
Urgent - Deck down!!!

### ISSUE THREAD

**Issue by SUPERNOVI** [sfx101/docker-stacks#166]
Hi all,

Deck is suddenly unable to launch. The app just has the logo animation repeating and nothing happens.

This might have to be the nail in the coffin for me as a user, first the SSL expiry and now this. Really need something more reliable.

Hope it can be fixed asap.

**Comment by sfx101** [comment]
@SUPERNOVI we are working on fixing this asap.

**Comment by sfx101** [comment]
@SUPERNOVI please restart the app, the issue should be fixed

**Comment by SUPERNOVI** [comment]
That's now working again.

What was the issue out of interest and will it happen again in the future?

**Comment by sfx101** [comment]
@SUPERNOVI When the app starts, it loads a JSON file to fetch "latest updates" from a URL. The SSL expired there.
We will make sure it doesn't happen in the future.
