### ISSUE TITLE
Create new stack/image

### ISSUE THREAD

**Issue by soarcn** [sfx101/docker-stacks#25]
Hi there,

Thanks for creating this beautiful tool to make my life easier.

I would like to create a Memcached stack and attach to the existing lnmp stack, is it possible? if so, how could I do it?

Thanks again for your effort
Cheers

**Comment by sfx101** [comment]
Hi @soarcn, thank you for trying it out!

To add Memcached to your lamp or lemp stack, please do the following

In the DECK UI, click on "More" beside your stack. Then "Configure" & "More advanced ..."

![image](https://user-images.githubusercontent.com/1749545/136941328-3aeeed55-7365-4260-b9da-059f779ae045.png)

1. Edit the file Dockefile-{The PHP version you've chosen, ex 7.4}
2. Add this line: `php7.4-memcached \`

![image](https://user-images.githubusercontent.com/1749545/136941644-e82b29b8-ce07-4150-b2f8-4b89950c5478.png)

3. Edit the file docker-compose.yml
4. Add these 2 lines after services: 

```
  memcached:
    image: memcached:latest
```

![image](https://user-images.githubusercontent.com/1749545/136941991-88901d77-9bed-4f8d-a8a3-b3092f610912.png)

Go, back to the DECK UI & rebuild the stack to connect to Memcached server

Here's an example code below to test if it working

```
<?php
$m = new Memcached();
$m->addServer('memcached', 11211);

$stats = $m->getStats();


echo "<pre>";

if ($stats)
    print_r($stats);
else
    echo "Connection error";
```
